Проект SHOP/store/products/urls.py
from django.urls import path

from products.views import products

app_name = 'products'

#Набор уникальных путей к именам файлов для перехода на отдельные стр

urlpatterns = [
    path('', products, name='index')
]

Проект SHOP/store/store/urls.py

from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Проект SHOP/store/users/urls.py
from django.urls import path

from users.views import login, register, profile, logout

app_name = 'users'

#Набор уникальных путей к именам файлов для перехода на отдельные стр

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
path('logout/', logout, name='logout')
]

#02.09.24

Проект SHOP/store/products/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    #Данное наследование показывает нам, что данное поле в БД будет иметь тип данных чарфилд
    name = models.CharField(max_length=256, unique=True)
    #Отличие чарфилда от текстфилда в том, что етксфилд принимамет в себя большое количество текста
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=0)
    #Количество товаров на складе
    quontity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Проект SHOP/store/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True)


Проект SHOP/store/users/forms.py
#28 # 02.09
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя',
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите фамилию',
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите имя пользователя',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите адрес эл. почты',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Подтвердите пароль',
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4'
    }))

    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }), required=False)

    username = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'readonly': True
    }))
    #02.09
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

Проект SHOP/store/products/views.py
from django.shortcuts import render

from products.models import ProductCategory, Product
def index(request):
    context = {
        'title': 'Store',
        'sale': 'Аутлет: до -70% Собственный бренд. -20% новым покупателям.',
        'is_sale': False,
    }
    return render(request, 'products/index.html', context)


def products(request):
    context = {
        'title': 'Store - Catalog',
        'products': Product.objects.all(),
        'categories': ProductCategory.objects.all()
    }
    return render(request, 'products/products.html', context)

Проект SHOP/store/users/views.py
from tempfile import template

from django.shortcuts import render, HttpResponseRedirect
# 26.08.24

#02.09, 0409
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib import auth, messages
from django.urls import reverse

from users.models import User
#Audit - контроль
#Authentification - подтверждение личности
#Authorisation - разрешение

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            #ау полшьзоват с определенным даннным даллее передаем аргументы имя и пароль
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)

#04.09
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались')
            return HttpResponseRedirect(reverse('users:login'))

    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)

# 02,09
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'title': 'Store - профиль', 'form': form }
    return render(request, 'users/profile.html', context)
#09.09
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))





Проект SHOP/store/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ title }} </title>

    {% block css%} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                            {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}



            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}
<!-- /.container -->

<!-- Footer -->
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

Проект SHOP/store/products/templates/products/index.html
{% extends 'products/base.html'%}

{% load static %}

{% block css%}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/index.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Page Content -->
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды .
                    Бесплатная доставка по всему миру!
                    {% if is_sale %}
                        {{ sale }}
                    {% endif %}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Проект SHOP/store/products/templates/products/products.html
{% extends 'products/base.html'%}

{% load static %}

{% block css %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="#" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }},00 руб.</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
<!-- /.container -->
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}

Проект SHOP/store/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

Проект SHOP/store/users/templates/users/login.html
{% extends 'users/base.html'%}

{% load static %}

{% block content %}
    <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                         <div class="alert
                         {% if messages %}
                                alert-success
                          {% else %}
                                alert-warning
                           {% endif %}
                             alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
<!--                            04.09-->
                             {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                             {% else %}
                                {{ form.non_field_errors }}
                             {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}

                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
<!--                                26.08-->
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
<!--                                    {{ form.as_p }}-->
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ forms.usename.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
<!--                                        <input class="form-control py-4" id="inputEmailAddress" type="text"-->
<!--                                               placeholder="Введите имя пользователя"/>-->
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ forms.password.id_for_label }}">
                                            Пароль

                                        </label>
<!--                                        <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                               placeholder="Введите пароль"/>-->
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}

Проект SHOP/store/users/templates/users/register.html
{% extends 'users/base.html'%}

{% load static %}

{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}

                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
<!--                            04.09 <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}

                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
<!--                                28.08-->
                                <form action="{% url 'users:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ forms.first_name.id_for_label }}">>
                                                    Имя
                                                </label>
                                            Имя пользователя
                                      {{ form.first_name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ forms.last_name.id_for_label }}">
                                                    Фамилия
                                                </label>
<!--                                                <input class="form-control py-4" id="inputLastName" type="text"-->
<!--                                                       placeholder="Введите фамилию"/>-->
                                                {{ form.last_name}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ forms.username.id_for_label }}">
                                                Имя пользователя
                                            </label>
<!--                                            <input class="form-control py-4" id="inputUsername" type="text"-->
<!--                                                   aria-describedby="usernameHelp"-->
<!--                                                   placeholder="Введите имя пользователя"/>-->
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ forms.email.id_for_label }}">
                                                Адрес электронно почты
                                            </label>
<!--                                            <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                                                   aria-describedby="emailHelp"-->
<!--                                                   placeholder="Введите адрес эл. почты"/>-->
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ forms.password1.id_for_label }}">
                                                    Пароль
                                                </label>
<!--                                                <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                                       placeholder="Введите пароль"/>-->
                                                 {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ forms.password2.id_for_label }}">
                                                    Подтверждение пароля
                                                </label>
<!--                                                <input class="form-control py-4" id="inputConfirmPassword"-->
<!--                                                       type="password" placeholder="Подтвердите пароль"/>-->
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}